# Base image
FROM jenkins/jenkins:lts

# Switch to root to install packages
USER root

# Update and install required tools
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    bc \
    docker.io

# Clean up to keep image small
RUN apt-get clean